### ISSUE TITLE
`unimplemented` without `Void` placeholder produces deprecation warning

### ISSUE THREAD

**Issue by hyperspacemark** [pointfreeco/swift-issue-reporting#122]
The following declaration produces a deprecation warning on the Swift 6 language mode only. I'm aware that the placeholder-less methods were deprecated but this seems to have only appeared after #114 was released.

```swift
var onCancel: () -> Void = unimplemented("ViewModel.onCancel") // warning: 'unimplemented(_:file:fileID:function:line:)' is deprecated: renamed to 'unimplemented(_:placeholder:)'
```

I can of course resolve the warning with the following but I don't think the intention is that this is necessary.

```swift
var onCancel: () -> Void = unimplemented("ViewModel.onCancel", placeholder: ())
```

**Comment by stephencelis** [comment]
This should be fixed by #123! We'll do a release soon.
