### ISSUE TITLE
TestContext.current is crashing on Xcode 16 RC1 (16A242)

### ISSUE THREAD

**Issue by JonLz** [pointfreeco/swift-issue-reporting#129]
I'm on version 1.3 of the package. This has previously worked on Xcode 16 beta 6 (16A5230g)

## Screenshot
![image](https://github.com/user-attachments/assets/810268dc-f187-4e4b-a64b-8d67e314b2b3)

## Zip file of an example project
[MyLibrary.zip](https://github.com/user-attachments/files/16966736/MyLibrary.zip)

**Comment by mbrandonw** [comment]
@JonLz Thanks for the report! We just released an update fixing this!
